type-complexity-threshold = 220
cognitive-complexity-threshold = 20
too-many-arguments-threshold = 8
too-many-lines-threshold = 360
doc-valid-idents = [
    "CommonJS",
    "ECMAScript",
    "NaN",
    "JavaScript",
    "TypeScript",
    "Infinity",
    "AST",
    "LSP",
    "WASM",
    "TSX",
    "JSX",
    "TypeId",
    "SymbolId",
    "DefId",
    "FlowNodeId",
    "TypeData",
    "ReadonlyArray",
    "TS",
    "JSDoc",
]
